#include<iostream>
#include<conio.h>

using namespace std;

/**
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

ans: 4613732
*/

int main(){
	
	int term = 0;
	
	int firstNum = 0;
	int secondNum = 1;
	int temp=0;
	long evenSum = 0;
	
	while(evenSum<4000000){
		
		temp = secondNum;
		secondNum = firstNum + secondNum;
		firstNum = temp;
		
		if(secondNum%2==0){
			evenSum += secondNum;
		}
			
	}
	
	cout << "sum of terms: " << evenSum;
	
	/*
	int i=1,j=1,sum=0;
	
    while(i<4000000){
    	i=i+j;
    	j=i-j;
    	
    	if(i%2==0)
    		sum+=i;
    }
    
	printf("Sum is: %d",sum);
	*/
	
	getch();
	return 0;
}
